server:
  port: 8080
  max_processors: 2 # sets GOMAXPROCS

logging:
  # available modes: text, json
  mode: text
  level: debug

cache:
  host: cache
  port: 6379

auth:
  issuer: jwt-microservice
  access_lifetime: 15m
  refresh_lifetime: 720h
  auto_logout: 24h
  passwords:
    min_length: 8
