services:
  jwt:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    command: ./main
    depends_on:
      cache:
        condition: service_healthy
    secrets:
      - jwt_key
    develop:
      watch:
        - action: rebuild
          path: ./cmd
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./internal
    deploy:
      resources:
        limits:
          cpus: '0.50'

  cache:
    container_name: jwt-cache
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s

  nginx:
    container_name: jwt-nginx
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jwt
    ports:
      - "4000:4000"

secrets:
  jwt_key:
    file: ./secrets/jwt_key.txt
