services:
  app:
    container_name: jwt-microservice
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ./main
    depends_on:
      cache:
        condition: service_healthy
    secrets:
      - jwt_key
    develop:
      watch:
        - action: rebuild
          path: ./cmd
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./internal

  cache:
    container_name: jwt-cache
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s

secrets:
  jwt_key:
    file: ./secrets/jwt_key.txt
