FROM golang:1.21-alpine as builder

RUN apk add --no-cache git
RUN go install go.k6.io/xk6/cmd/xk6@latest

WORKDIR /build
RUN xk6 build --output /k6 --with github.com/grafana/xk6-dashboard@latest

FROM grafana/k6:latest
COPY --from=builder /k6 /usr/bin/k6
ENTRYPOINT ["k6"]
