name: Go CI

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and update coverage badge
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Install dependencies
        run: go mod download

      - name: Run tests and save results and coverage
        run: |
          go test -v ./... -coverprofile=coverage.out -covermode=atomic -json > TestResults.json
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            TestResults.json
            coverage.html
